name: Changelog generator 
description: Github Changelog/History Generator
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  output:
    description: 'Output file'
    required: false
    default: "CHANGELOG.md"

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.output }}
branding:
  icon: file-text
  color: white
